### PR TITLE
drop 2.6 support, fix a broken image.

### PR DESCRIPTION
**Pull request by reaperhulk**

### CODE REVIEW

**Comment by alex** [comment]
Do we have data supporting that it's ok to drop 2.6?

**Comment by reaperhulk** [comment]
Yep, sorry, forgot to cross link #202.

**Comment by alex** [comment]
👍  is there any 2.6 compat code that needs to be deleted?

**Comment by reaperhulk** [comment]
I'm not aware of any. Coverage is a bit lower than it should be in general so I'll probably be submitting some PRs for that next week.

**Pull request merged**
