### PR TITLE
return the byte string as a str in py3

### LINKED ISSUE #205: SecretBox.__unicode__() attribute missing for Py3
Try to `print()` a SecretBox object and you get the following:

```
../python3.4/site-packages/nacl/utils.py", line 54, in __str__
    return self.__unicode__()
AttributeError: 'SecretBox' object has no attribute '__unicode__'
```

### PR DESCRIPTION
**Pull request by reaperhulk**
This encodes it a bit, but you shouldn't be printing things except for debug anyway.

Fixes #205

### CODE REVIEW

**Comment by blag** [comment]
This looks perfectly cromulent to me.

**Comment by lmctv** [comment]
@reaperhulk if we should keep the StringFixer mix-in, this LGTM.

**Comment by reaperhulk** [comment]
I honestly don't remember the context for why I decided this was a better approach than stripping out that mixin... If you're comfortable with it then we can merge it and move forward. We can always revisit if necessary.

**Comment by lmctv** [comment]
@reaperhulk I think It's better if we just fix this for the time being, an later decide when to insert a explicit deprecation leading to the removal of the mixin usage.

@reaperhulk @alex how should I do the merge? Github web gui "Squash and merge" button, or local merge/squash followed by upstream push?

**Comment by reaperhulk** [comment]
Squash and merge in the GitHub UI is how we merge. We have the master branch protected so direct pushes aren't possible without status checks passing.

**Comment by lmctv** [comment]
OK, it was about time!

**Pull request merged**
