### PR TITLE
ARM64 Support to Github Actions for wheel development

### PR DESCRIPTION
**Pull request by odidev**
Added ARM64 Support to Github Actions for wheel development.
Resolves the second step for #601 

@reaperhulk Please review and let me know if any changes required.

### CODE REVIEW

**Comment by reaperhulk** [comment]
How long does this take in your tests?

**Comment by odidev** [comment]
@reaperhulk, It is taking 41mins to complete aarch64 wheel builder pipeline.

**Comment by odidev** [comment]
@reaperhulk , Could you please review the PR and give me your suggestions and feedback.
Thanks in advance.

**Comment by reaperhulk** [comment]
This approach is too slow unfortunately. If we used this there would be a 40+ minute window where, after a release, a new sdist was available but no wheels would be. We do have access to graviton2 now that we've migrated our org, but we'll have to change our wheel building approach to happen automatically on tag (and sort out how we want to handle pypi tokens) to switch to that model.

**Comment by ianw** [comment]
> This approach is too slow unfortunately. If we used this there would be a 40+ minute window where, after a release, a new sdist was available but no wheels would be. We do have access to graviton2 now that we've migrated our org, but we'll have to change our wheel building approach to happen automatically on tag (and sort out how we want to handle pypi tokens) to switch to that model.

I will be happy to work the existing OpenDev Zuul wheel builds into this repository as well, if that would be OK.  We can share most of the roles and make the jobs generic.  I think the Zuul bot would just need to be enabled here too.

Zuul could definitely upload sdists and linux wheels automatically on tags.  Unfortunately we don't have anywhere to build osx and windows though.  So I understand you want to keep everything together, but the offer is there :) 

> and sort out how we want to handle pypi tokens

FYI Zuul handles secrets for situations like this with the idea of post-review pipelines (https://zuul-ci.org/docs/zuul/reference/secret_def.html).  Zuul exports a key for each repo which you can encode a secret with (https://zuul-ci.org/docs/zuul/discussion/encryption.html); i.e. you keep the secret encrypted in your public job definitions and Zuul can decrypt it as it needs to.  You can only use that secret in trusted places -- i.e. the post-review release pipeline, that happens in response to tag events.  If a change has been tagged, then it's assumed only an authorized person has done that, and the tagged code has been reviewed and committed so is not doing anything silly like saying "hey, print out the value of this secret for me".  You obviously can not submit a pull request (that executes speculatively) that dumps a secret as that isn't a trusted context.

So in short, if the project added the openstackci pypi user, I could encrypt the secret I know for that, and we'd have a release pipeline job that would uploading using it.

**Comment by odidev** [comment]
May I know, when the migration form travis-ci.org to travis-ci.com will be done? This PR is blocked and waiting for the migration to be completed.

**Comment by reaperhulk** [comment]
It's already done. I think changing wheel building here looks something like this. To do a release we push a new tag. That tag triggers a workflow that does the following:
* Uploads the sdist as one job
* In parallel generates sdists from the checked out source from tag (we always want to work from a generated sdist) and then builds and uploads wheels

Even if the wheel building is slow this is okay because each wheel will be uploaded as they finish (instead of waiting until the slowest finishes in our current system).

This is probably easiest to implement with a minimum of changes on GitHub Actions, but would be faster on Travis since we have access to Graviton2 builders there.

**Comment by odidev** [comment]
@reaperhulk I would be happy to add travis support for building wheels for pynacl. Would you like me to raise me a PR for the same?

**Comment by odidev** [comment]
@reaperhulk, could you please let me know your interest on adding Travis-ci support for releasing wheels.

**Comment by lopezm1** [comment]
@odidev Appreciate you following up and taking this on for the community. Our group just came across this issue and are interested in the release of it too.

**Comment by odidev** [comment]
@lopezm1, thanks for your response. It seems, pynacl no longer uses travis-ci as CI/CD and I have already raised this PR for building/deploying aarch64 wheels. Can you please let me know what else is required here from my side. Thanks

**Comment by odidev** [comment]
@lopezm1, can you please let me know if anything is required here from my side?
CC: @reaperhulk

**Comment by reaperhulk** [comment]
We aren't going to merge any wheel builders that don't have corresponding CI, and we have no access to aarch64 hardware within GitHub Actions at this time. We could potentially look towards opendev (which we use on the cryptography side), but the reliability of that platform has been moderately frustrating for us.

**Comment by odidev** [comment]
> aren't going to merge any wheel builders that don't have corresponding CI,

Please let me know your interest in running CI tests in qemu emulation environment. I will work on the same.

**Comment by reaperhulk** [comment]
You implemented qemu based CI and in https://github.com/pyca/pynacl/pull/612#issuecomment-682595142 I noted that the performance is simply not acceptable for us. 40+ minute CI is not tenable.

**Comment by joekohlsdorf** [comment]
I would agree that 40 minutes would be too much if you released multiple times per day but that is not the case at all.
Why would you make the sdist available on PyPI before all wheels are built? As far as I can see, uploading to PyPI is not part of the CI pipeline and nobody is pulling Python source releases from GitHub.

**Comment by dennisameling** [comment]
FWIW, CircleCI has [free Linux arm64 runners](https://circleci.com/docs/2.0/arm-resources/) available since a few months 😊

**Comment by reaperhulk** [comment]
@dennisameling thanks for the suggestion! I'm looking into that on `pyca/cryptography` based on your comment (https://github.com/pyca/cryptography/pull/6763). It appears to do what we need so once that lands we'll probably port it here as well.

**Comment by reaperhulk** [comment]
This is now provided natively by circleci (until actions adds support for native arm at least)

**Pull request closed without merging**
