### PR TITLE
Add crypto pwhash scryptsalsa208sha256

### PR DESCRIPTION
**Pull request by malthe**

### CODE REVIEW

**Comment by reaperhulk** [comment]
Looks like there's a py3 str/bytes issue to resolve in the tests.

**Comment by alex** [comment]
I think this would be the first feature we're using that is from libsodium, vs. nacl itself?

**Comment by malthe** [comment]
@reaperhulk doh ... fixed :-)

**Comment by gleb-chipiga** [comment]
With with this pull request? Password hashing is very useful functionality

**Comment by reaperhulk** [comment]
closing in favor of #204

**Pull request closed without merging**
