### PR TITLE
Switch to using CFFI 1.0 APIs

### PR DESCRIPTION
**Pull request by dstufft**

### CODE REVIEW

**Comment by reaperhulk** [comment]
For this to pass travis you'll have to do the pypy2.6 pyenv workaround we did for cryptography and bcrypt :(

**Comment by reaperhulk** [comment]
Oh god, how did we let this sit so long :sob: 

@dstufft could you rebase this?

**Comment by dstufft** [comment]
Unlikely I'm going to find time to do it in the next couple of weeks.

**Comment by reaperhulk** [comment]
Okay, I'll probably take this over then unless anybody else wants to volunteer.

**Comment by reaperhulk** [comment]
Closing in favor of #155

**Pull request closed without merging**
