### PR TITLE
[RFC] Replace standard library exceptions with nacl defined ones

### PR DESCRIPTION
**Pull request by lmctv**

### CODE REVIEW

**Comment by reaperhulk** [comment]
Interested in @warner's opinion here

**Comment by lmctv** [comment]
@warner would you mind doing a review of this PR?

**Comment by lmctv** [comment]
Rebased on efe0f83b3c2bfd163a5a1338027bb0e2daee7984 to solve merge conflict in ``crypto_shorthash_siphash24``

**Comment by lmctv** [comment]
@reaperhulk do you think you can reach @warner and try to nudge him in reviewing this PR?

**Comment by reaperhulk** [comment]
I don't have a great way to do that outside of pinging on github, sorry. Is this the last PR we want for 1.1.0?

**Comment by lmctv** [comment]
While all changes have been done in a backwards-compatible way, I wouldn't like seeing a change like this one in a third-digit release, therefore I'd prefer if this could get in 1.1.0 , which I think can be seen as complete by now. In case a delay is needed, I could try and paste a couple of lines from my comments on #233 to help in planning a possible future migration from scrypt to argon2i .

**Comment by lmctv** [comment]
@reaperhulk I've just added another couple of "nice to have in 1.1" PRs:
#263 is mostly a cut-and paste from the suggestions I gave to @itdaniher in #233 on how to plan a transition from scrypt to argon2i
#264 changes, while really idempotent are a correctness upgrade

**Comment by blag** [comment]
I am very much in favor of this.

**Comment by lmctv** [comment]
@alex , @dstufft do you think you spare some cycles to review this PR, or at least comment on the idea of only raising nacl.exceptions.CryptoError subclasses, as requested by @reaperhulk, since it seems @warner isn't able to find the needed time just now?

Thank you very much, and sorry for bothering!

**Pull request merged**
