### PR TITLE
Add argon2i hashes generated via the command line

### PR DESCRIPTION
**Pull request by lmctv**
This is a prerequisite for an upcoming PR meant to add argon2i bindings and closing #233.

@reaperhulk I don't think the python driver I've used to generate the reference data should be added in, but I'm open to any suggestion.

### CODE REVIEW

**Comment by reaperhulk** [comment]
Drop it in a comment here so I can confirm the vectors locally.

**Comment by lmctv** [comment]
If you think it's needed, I'll replace  calls ti systemrandom with calls to come deterministic PRNGs and resubmit.

**Comment by reaperhulk** [comment]
Eh, no. If you have the code ready that verifies these vectors using the argon2i bindings in libsodium maybe submit that though? Once those tests pass I'm okay with merging this and then you can rebase.

Would be nice if the argon2 official repo's test vectors were more useful for this scenario...

**Comment by lmctv** [comment]
I hope to have test code running by tomorrow at last..

**Comment by lmctv** [comment]
I've replaced the raw hashes since libsodium forces a fixed length for the salt, and doesn't expose a wrapper for the low-level argon2i construct; while I respectfully disagree with this choice jedisct1/libsodium#488, I think we can only adapt and lower our expectations...

**Comment by lmctv** [comment]
The test vectors got already in via #261

**Pull request closed without merging**
