### PR TITLE
RFC: use "bag of constants" classes to group parameters related to the same construct

### PR DESCRIPTION
**Pull request by lmctv**
I've left compatible module-level names for constructs released in 1.1 , which should be deprecated and then removed if the enum idea flies.

### CODE REVIEW

**Comment by alex** [comment]
Use of enum does not make sense here, an enum is a type, where it shoudl be valid to pass any of it's values in a given context, that's not what these are, these are just unrelated constants.

-1 from me.

**Comment by lmctv** [comment]
@alex thank you very much for refreshing my memory on the difference between enumerations and attribute bags!
Would you mind taking another look, now that I defined and used a Constant bag-of-attributes class?

**Comment by lmctv** [comment]
Just rebased on the add-argon2id PR and added the needed corrections to the docs.

**Comment by lmctv** [comment]
Useless. Replaced by #357

**Pull request closed without merging**
