### PR TITLE
Support building PyNACL on Apple Silicon

### PR DESCRIPTION
**Pull request by carlosonunez**
This adds a mapping for Apple Silicon CPUs.

### CODE REVIEW

**Comment by carlosonunez** [comment]
This fixes #657

**Comment by alex** [comment]
This file is from libsodium itself and should not be modified here. If a change is required in libsodium, it should be made upstream.

**Comment by carlosonunez** [comment]
Sorry about that. I'll make the modification there.

**Comment by carlosonunez** [comment]
For future reference: `libsodium` pulls this list from https://savannah.gnu.org/. This list was updated recently (as of this time of writing), but the version of `libsodium` included here has an outdated list.

**Comment by reaperhulk** [comment]
#680 should help with this once we do the 1.5.0 release.

**Comment by carlosonunez** [comment]
Amazing!

**Comment by xpnewmedia** [comment]
How do i make this work on M1?

**Comment by expelledboy** [comment]
> #680 should help with this once we do the 1.5.0 release.

When will it be released?

**Comment by xpnewmedia** [comment]
can anyone help me get a working install of pyNACL on m1 MacBook?

**Pull request closed without merging**
