### PR TITLE
Low-level support for ed25519ph streaming signature

### PR DESCRIPTION
**Pull request by lmctv**
In partial fulfillment of #347.

### CODE REVIEW

**Comment by lmctv** [comment]
@reaperhulk I'm unable to understand the jenkins failure, especially since both
https://ci.cryptography.io/blue/organizations/jenkins/pyca%2Fpynacl/activity?branch=PR-380
and
https://ci.cryptography.io/blue/organizations/jenkins/pyca%2Fpynacl/detail/master/64/pipeline/
were OK

**Comment by reaperhulk** [comment]
This is a bug in virtualenv triggered by the latest cffi release. They’re planning to revert, but we could merge a blacklist for 1.11.3 to fix it now if we want (we did that on cryptography)

**Comment by lmctv** [comment]
Test passed. I think this is ready for review.

**Comment by lmctv** [comment]
Rebased on 3b89b41a654d36fa887c3cf2f6632659397b2aa9 to run tests on updated libsodium version.

**Comment by lmctv** [comment]
@reaperhulk do you think you'll be able to find some spare time to take a look at this PR?

**Comment by lmctv** [comment]
@reaperhulk ping?

**Comment by reaperhulk** [comment]
I probably won't be able to get to this until next week. Keep the pings coming though because I am terrible at to do lists 😂

**Comment by lmctv** [comment]
@reaperhulk as requested... Sending this week's ping.

**Comment by lmctv** [comment]
@reaperhulk weekly ping.

**Pull request merged**
