### PR TITLE
Upgrade libsodium to 1.0.1

### LINKED ISSUE #120: Upgrade libsodium to 1.0.1

### PR DESCRIPTION
**Pull request by reaperhulk**
Fixes #120 

As mentioned in that issue upgrading this just requires getting the latest tarball and replacing the libsodium directory. Arguably we shouldn't even untar it but since we currently do I have stayed consistent.

### CODE REVIEW

**Comment by Ayrx** [comment]
Is it much work to make it a tarball instead? Ref #49.

**Comment by alex** [comment]
libsodium 1.0.2 is now out, want to bump tot hat?

**Comment by malthe** [comment]
Bump. Merge?

**Comment by warner** [comment]
The contents of src/libsodium/src match the upstream 1.0.1 tarball from http://download.libsodium.org/libsodium/releases/ (signed by GPG key 54A2B8892CC3D6A597B92B6C210627AABA709FE1). They also match the 1.0.1 tag of https://github.com/jedisct1/libsodium/ (on git revision 2ee447ff1412878dd69d0692e256b8ddd4269939).

Tests pass locally, and Travis is happy. I'll merge.

After the release, let's figure out how to use a tarball instead of the unpacked files (#123).

**Pull request merged**
